for:
    'residuos': 'QaVrI6ru'
    rules:
    -
        verbs: [card, per]
        move:
            to: '5457a441ed9d1bc0e679f066'
        comment: true
    -
        verbs: [close, closes]
        move:
            to: '5457a445b07eb550b951d313'
        comment: true
